import Head from 'next/head'
import Image from 'next/image'
import About from '../components/About'
import Contact from '../components/Contact'
import Intro from '../components/Intro'
import Portfolio from '../components/Portfolio'
import Skill from '../components/Skill'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Dennis Pradana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/resume.png" />
      </Head>

      <Intro/>
      <About/>
      <Skill/>
      <Portfolio/>
      <Contact/>
      
    </div>
  )
}
